### ISSUE TITLE
Precompiled Mac version can't find pkg_resources.py2_warn

### ISSUE THREAD

**Issue by chz16** [frozenpandaman/splatnet2statink#107]
Trying to run the precompiled version of 1.5.6 on macOS 10.14.6 dies with this trace:

```
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pkg_resources/__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[32839] Failed to execute script pyi_rth_pkgres
```

Might be a Setuptools thing? https://github.com/pypa/setuptools/issues/1963

**Comment by frozenpandaman** [comment]
Oops, sorry about that, and thanks! Seems I still had PyInstaller 3.5 installed. Just upgraded to 4.0 and rebuilt it, and tested to make sure it works – and it does now! Just updated zip on the [releases page](https://github.com/frozenpandaman/splatnet2statink/releases). Thanks again for catching this!
