### ISSUE TITLE
UnboundLocalError: local variable 'acc_name' referenced before assignment

### ISSUE THREAD

**Issue by gomtuu** [frozenpandaman/splatnet2statink#74]
In v1.4.0, after manually entering an iksm_session cookie, I get an error:

```
Traceback (most recent call last):
  File "./splatnet2statink.py", line 1255, in <module>
    monitor_battles(is_s, is_t, is_r, m_value, debug)
  File "./splatnet2statink.py", line 367, in monitor_battles
    results = load_results("monitor") # make sure we can do it first. if error, throw it before main process
  File "./splatnet2statink.py", line 322, in load_results
    gen_new_cookie(reason)
  File "./splatnet2statink.py", line 138, in gen_new_cookie
    print("Wrote iksm_session cookie for {} to config.txt.".format(acc_name))
UnboundLocalError: local variable 'acc_name' referenced before assignment
```

Looks like `acc_name` is only defined if `manual` is false, because it's the name of the Nintendo account used for automatic cookie generation.

Despite the error, the config file is updated properly and the program works the next time I run it.

Thanks!

**Comment by frozenpandaman** [comment]
Oops. Silly mistake. Fixed in 3ba2870 (v1.4.1). Thanks @gomtuu!
